### PR TITLE
Add Makefile to ease up building vcd

### PR DESCRIPTION
**Pull request by UffeJakobsen**

### CODE REVIEW

**Comment by yne** [comment]
Thanks for the PR

I'm not sure if a makefile is necessary for a single file project.

also, where is the `cc` invocation ?

**Comment by UffeJakobsen** [comment]
>  I'm not sure if a makefile is necessary for a single file project.

Well - it would ease up the life for any package maintainer as the package script would not have to deal with specific file names for compiling and installing into stage area etc...
Generic `make all`, `make install [DESTDIR=/some/path]` and `make clean`could be used - and the package file becomes more generic - like a template - that is nice if you as a package maintainer is dealing with 10's or 100's or 1000's of packages 

> also, where is the `cc` invocation ?

It relies on implicit rules - default rules if you like
https://www.gnu.org/software/make/manual/html_node/Catalogue-of-Rules.html#Catalogue-of-Rules

If you like explicit rules can be introduced

**Comment by yne** [comment]
thanks

let's hope maintainers will use this new build system in they packages ;)

**Comment by UffeJakobsen** [comment]
> 
> let's hope maintainers will use this new build system in they packages ;)

I've already updated the archlinux AUR package to the new approach - thank you :-)  :+1:

**Pull request merged**
